"""init

Revision ID: 3c9c39630175
Revises: 
Create Date: 2025-11-28 01:56:52.795334
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c9c39630175'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('total_likes', sa.Integer(), nullable=False),
    sa.Column('total_works', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('dialogues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dialogues_user_id'), 'dialogues', ['user_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('generate_music', 'analyze_emotion', name='tasktype'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='taskstatus'), nullable=False),
    sa.Column('input', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.create_table('user_followers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('following_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['following_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_id', 'following_id', name='uq_follow_pair')
    )
    op.create_index(op.f('ix_user_followers_follower_id'), 'user_followers', ['follower_id'], unique=False)
    op.create_index(op.f('ix_user_followers_following_id'), 'user_followers', ['following_id'], unique=False)
    op.create_table('music_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dialogue_id', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('file_type', sa.String(length=20), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dialogue_id'], ['dialogues.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_music_files_dialogue_id'), 'music_files', ['dialogue_id'], unique=False)
    op.create_index(op.f('ix_music_files_user_id'), 'music_files', ['user_id'], unique=False)
    op.create_table('dialogue_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dialogue_id', sa.Integer(), nullable=False),
    sa.Column('music_file_id', sa.Integer(), nullable=True),
    sa.Column('user_input_text', sa.Text(), nullable=True),
    sa.Column('system_reply_text', sa.Text(), nullable=True),
    sa.Column('message_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dialogue_id'], ['dialogues.id'], ),
    sa.ForeignKeyConstraint(['music_file_id'], ['music_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dialogue_messages_dialogue_id'), 'dialogue_messages', ['dialogue_id'], unique=False)
    op.create_index(op.f('ix_dialogue_messages_music_file_id'), 'dialogue_messages', ['music_file_id'], unique=False)
    op.create_table('emotion_analysis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('music_file_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('main_emotion', sa.String(length=50), nullable=True),
    sa.Column('emotion_intensity', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('arousal_level', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('raw_result', sa.JSON(), nullable=True),
    sa.Column('report_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['music_file_id'], ['music_files.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emotion_analysis_music_file_id'), 'emotion_analysis', ['music_file_id'], unique=False)
    op.create_index(op.f('ix_emotion_analysis_user_id'), 'emotion_analysis', ['user_id'], unique=False)
    op.create_table('works',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('music_file_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('draft', 'published', name='workstatus'), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('play_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['music_file_id'], ['music_files.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_works_music_file_id'), 'works', ['music_file_id'], unique=False)
    op.create_index(op.f('ix_works_user_id'), 'works', ['user_id'], unique=False)
    op.create_table('like_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'work_id', name='uq_user_work_like')
    )
    op.create_index(op.f('ix_like_records_user_id'), 'like_records', ['user_id'], unique=False)
    op.create_index(op.f('ix_like_records_work_id'), 'like_records', ['work_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_like_records_work_id'), table_name='like_records')
    op.drop_index(op.f('ix_like_records_user_id'), table_name='like_records')
    op.drop_table('like_records')
    op.drop_index(op.f('ix_works_user_id'), table_name='works')
    op.drop_index(op.f('ix_works_music_file_id'), table_name='works')
    op.drop_table('works')
    op.drop_index(op.f('ix_emotion_analysis_user_id'), table_name='emotion_analysis')
    op.drop_index(op.f('ix_emotion_analysis_music_file_id'), table_name='emotion_analysis')
    op.drop_table('emotion_analysis')
    op.drop_index(op.f('ix_dialogue_messages_music_file_id'), table_name='dialogue_messages')
    op.drop_index(op.f('ix_dialogue_messages_dialogue_id'), table_name='dialogue_messages')
    op.drop_table('dialogue_messages')
    op.drop_index(op.f('ix_music_files_user_id'), table_name='music_files')
    op.drop_index(op.f('ix_music_files_dialogue_id'), table_name='music_files')
    op.drop_table('music_files')
    op.drop_index(op.f('ix_user_followers_following_id'), table_name='user_followers')
    op.drop_index(op.f('ix_user_followers_follower_id'), table_name='user_followers')
    op.drop_table('user_followers')
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_dialogues_user_id'), table_name='dialogues')
    op.drop_table('dialogues')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
